#!/bin/sh
#PBS -l walltime=24:00:00,nodes=1:ppn=1,mem=2gb
#PBS -o /home/watkinse/qiuxx221/Result_files/Isoseq/out
#PBS -e /home/watkinse/qiuxx221/Result_files/Isoseq/error
#PBS -N gzip
#PBS -M qiuxx221@umn.edu
#PBS -m abe
#PBS -r n

cd /home/watkinse/qiuxx221/Sequencing_reads/Fungicide_Project/TP2
gzip F_T1_2_R1_trimmed_1.fastq
gzip F_T1_2_R2_trimmed_2.fastq
gzip F_T1_3_R1_trimmed_1.fastq
gzip F_T2_1_R1_trimmed_1.fastq
gzip F_T2_1_R2_trimmed_2.fastq
gzip F_T2_2_R1_trimmed_1.fastq
gzip F_T2_2_R2_trimmed_2.fastq
gzip F_T2_3_R1_trimmed_1.fastq 
gzip F_T2_3_R2_trimmed_2.fastq  
gzip W_T2_1_R1_trimmed_1.fastq
gzip W_T2_1_R2_trimmed_2.fastq
gzip W_T2_2_R1_trimmed_1.fastq
gzip W_T2_2_R2_trimmed_2.fastq
gzip W_T2_3_R1_trimmed_1.fastq
gzip W_T2_3_R2_trimmed_2.fastq
